### ISSUE TITLE
resume and clear button

### ISSUE THREAD

**Issue by MarieHilaryHerrera** [MarieHilaryHerrera/EEE_Coderist#2]
the text for clock frame should be 00:00:00

places for every button 
        start_button.place(x=100,y=300, width=150,height=50)
        lap_button.place(x=730,y=300, width=150,height=50)
        reset_button.place(x=415,y=300, width=150,height=50)
        clock_frame.place(x=200,y=100, width=600,height=100)

**Comment by Safara24** [comment]
Okay po, noted. Follow ko lang yan para sa code
