### ISSUE TITLE
lap button and finalize 

### ISSUE THREAD

**Issue by MarieHilaryHerrera** [MarieHilaryHerrera/EEE_Coderist#3]
*for the label 
bg= white, fg= black and font= 100
*for the rest of the buttons
bg= white, fg= black and font= 20

Ps. it's up to you on what will you put for the text name

**Comment by LouiseMayy** [comment]
Noted. I'll use default font (Arial) for the texts.

**Comment by MarieHilaryHerrera** [comment]
Hi ate, done na po si saf so you can proceed na po.
